# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20171107_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
